// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExBinding.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MKO_CPU850_RED_CPU850_MONO")]
    public partial class MKO_CPU850_RED_CPU850_MONOFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "MKO_cpu850Red_cpu850Mono.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "MKO_CPU850_RED_CPU850_MONO", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MKO_cpu850Red_cpu850Mono_RuntimeCheak")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_CPU850")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MKO_Cpu850Red_Cpu850Mono_RuntimeCheak()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_CPU850",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MKO_cpu850Red_cpu850Mono_RuntimeCheak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 13
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
 testRunner.Given("Связь с устройством \'CPU850_MONO\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 16
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_BOOL\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_DINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_INT\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_LINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 20
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_LREAL\'.\'\' с \'CPU850_RED\'.\'resVa" +
                        "r_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_REAL\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_SINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_UDINT\'.\'\' с \'CPU850_RED\'.\'resVa" +
                        "r_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_UINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_ULINT\'.\'\' с \'CPU850_RED\'.\'resVa" +
                        "r_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_SF_USINT\'.\'\' с \'CPU850_RED\'.\'resVa" +
                        "r_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_DINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_INT\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_LINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_re" +
                        "sVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_REAL\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_SINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_re" +
                        "sVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_UINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_re" +
                        "sVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
 testRunner.Then("Сравниваю значение \'MKO_CPU850_MONO_CPU850_RED_RT_USINT\'.\'\' с \'CPU850_RED\'.\'RT_re" +
                        "sVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 44
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'resVar_I" +
                        "NT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 49
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'resVar_" +
                        "UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_SF_CONTROL_USINT\'.\'\' с \'CPU850_RED\'.\'resVar" +
                        "_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 57
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'RT_resVa" +
                        "r_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 61
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'RT_resV" +
                        "ar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 64
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
 testRunner.Then("Сравниваю значение \'MKO_CPU850_CPU850_RT_CONTROL_USINT\'.\'\' с \'CPU850_RED\'.\'RT_res" +
                        "Var_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MKO_cpu850Red_cpu850Mono_ArchiveCheck")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_CPU850")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MKO_Cpu850Red_Cpu850Mono_ArchiveCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_CPU850",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MKO_cpu850Red_cpu850Mono_ArchiveCheck", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 77
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 78
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
 testRunner.Given("Соединение с 1 Архивом \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 80
 testRunner.Given("Связь с устройством \'CPU850_MONO\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
 testRunner.Given("Соединение с 2 Архивом \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 83
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_BOOL\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_DINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_INT\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_LINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_LREAL\'.\'\' с \'CPU850_RED\'" +
                        ".\'resVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_REAL\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 89
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_SINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_UDINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'resVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_UINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_ULINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'resVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_SF_USINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'resVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 95
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_BOOL\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_DINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_INT\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_LINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_LREAL\'.\'\' с \'CPU850_RED\'" +
                        ".\'RT_resVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_REAL\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_SINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_UDINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'RT_resVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_UINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_ULINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'RT_resVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_MONO_CPU850_RED_RT_USINT\'.\'\' с \'CPU850_RED\'" +
                        ".\'RT_resVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 108
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 110
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 111
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'r" +
                        "esVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 114
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 116
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 118
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 119
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 120
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_SF_CONTROL_USINT\'.\'\' с \'CPU850_RED\'." +
                        "\'resVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 122
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 124
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'R" +
                        "T_resVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 126
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 127
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 128
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 129
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'" +
                        "RT_resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 131
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
 testRunner.Then("Сравнение архивных данных \'MKO_CPU850_CPU850_RT_CONTROL_USINT\'.\'\' с \'CPU850_RED\'." +
                        "\'RT_resVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MKO_cpu850Red_cpu850Mono_ErrorCheck")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_CPU850")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MKO_Cpu850Red_Cpu850Mono_ErrorCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_CPU850",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MKO_cpu850Red_cpu850Mono_ErrorCheck", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 141
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 144
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 145
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 147
 testRunner.Then("Сравниваю значение \'CPU850_CPU850_SF_ERRORCNT\'.\'\' с допустимым \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 148
 testRunner.Then("Сравниваю значение \'CPU850_CPU850_RT_ERRORCNT\'.\'\' с допустимым \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
