// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExBinding.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MPO_CPU850_RESOURCE")]
    public partial class MPO_CPU850_RESOURCEFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "MPO_cpu850Red_Resource.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "MPO_CPU850_RESOURCE", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MPO_cpu850Red_Resource_RuntimeCheak")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_Resource")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MPO_Cpu850Red_Resource_RuntimeCheak()
        {
            string[] tagsOfScenario = new string[] {
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_Resource",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MPO_cpu850Red_Resource_RuntimeCheak", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 15
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_BYTE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BYTE\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_DATE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DATE\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_DINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_DWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DWORD\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 20
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_INT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_LINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LREAL\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_LWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LWORD\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_REAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_SINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_TIME\'.\'\' с \'CPU850_RED\'.\'RT_resVar_TIME\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UDINT\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_UINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_ULINT\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_USINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_USINT\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
 testRunner.Then("Сравниваю значение \'BIND_LOOP_SF_RT_WORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_WORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BOOL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_BYTE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BYTE\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_DATE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DATE\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_DWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DWORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LREAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_LWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LWORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_REAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 44
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_SINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_TIME\'.\'\' с \'CPU850_RED\'.\'RT_resVar_TIME\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UDINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_ULINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 49
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_USINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_USINT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
 testRunner.Then("Сравниваю значение \'BIND_CONTROL_WORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_WORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MPO_cpu850Red_Resource_ArchiveCheck")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_Resource")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MPO_Cpu850Red_Resource_ArchiveCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_Resource",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MPO_cpu850Red_Resource_ArchiveCheck", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
 testRunner.Given("Соединение с 1 Архивом \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 65
 testRunner.Given("Соединение с 2 Архивом \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 67
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BOO" +
                        "L\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_BYTE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BYT" +
                        "E\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 69
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_DATE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DAT" +
                        "E\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_DINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DIN" +
                        "T\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_DWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DW" +
                        "ORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_INT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_INT\'" +
                        ".\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 73
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_LINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LIN" +
                        "T\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LR" +
                        "EAL\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 75
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_LWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LW" +
                        "ORD\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_REAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_REA" +
                        "L\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_SINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_SIN" +
                        "T\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_TIME\'.\'\' с \'CPU850_RED\'.\'RT_resVar_TIM" +
                        "E\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UD" +
                        "INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_UINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UIN" +
                        "T\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UL" +
                        "INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_USINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_US" +
                        "INT\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
 testRunner.Then("Сравнение архивных данных \'BIND_LOOP_SF_RT_WORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_WOR" +
                        "D\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_BOOL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BOOL\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_BYTE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_BYTE\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_DATE\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DATE\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 89
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_DINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DINT\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_DWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_DWORD" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_INT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_INT\'.\'\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_LINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LINT\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_LREAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LREAL" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_LWORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_LWORD" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 95
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_REAL\'.\'\' с \'CPU850_RED\'.\'RT_resVar_REAL\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_SINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_SINT\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_TIME\'.\'\' с \'CPU850_RED\'.\'RT_resVar_TIME\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_UDINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UDINT" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_UINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_UINT\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_ULINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_ULINT" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_USINT\'.\'\' с \'CPU850_RED\'.\'RT_resVar_USINT" +
                        "\'.\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
 testRunner.Then("Сравнение архивных данных \'BIND_CONTROL_WORD\'.\'\' с \'CPU850_RED\'.\'RT_resVar_WORD\'." +
                        "\'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MPO_Cpu850Red_Resource_ErrorCheck")]
        [NUnit.Framework.CategoryAttribute("EpicМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("parentSuiteРасширенный_функционал_ПЛК")]
        [NUnit.Framework.CategoryAttribute("suiteМКО/МРО")]
        [NUnit.Framework.CategoryAttribute("subSuiteCPU850_Resource")]
        [NUnit.Framework.CategoryAttribute("critical")]
        public void MPO_Cpu850Red_Resource_ErrorCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "EpicМКО/МРО",
                    "parentSuiteРасширенный_функционал_ПЛК",
                    "suiteМКО/МРО",
                    "subSuiteCPU850_Resource",
                    "critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MPO_Cpu850Red_Resource_ErrorCheck", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 113
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 114
 testRunner.Given("Связь с устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 116
 testRunner.Then("Сравниваю значение \'BindingLoop_ErrorCnt\'.\'\' с допустимым \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
