// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExchangeUtils.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GwE2ex_Archive")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    [NUnit.Framework.CategoryAttribute("Archive")]
    public partial class GwE2Ex_ArchiveFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "ignore",
                "Archive"};
        
#line 1 "old_GwE2ex_Archive.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "GwE2ex_Archive", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.iCore2_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_ICore2_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.iCore2_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.Given("Связь с 1 устройством \'ICORE2\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 12
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 15
 testRunner.When("Чтение исходных архивных данных \'resVar_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
    testRunner.Then("Сравнение архивных данных \'iCore2_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
    testRunner.When("Чтение исходных архивных данных \'resVar_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
    testRunner.Then("Сравнение архивных данных \'iCore2_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
    testRunner.When("Чтение исходных архивных данных \'resVar_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
    testRunner.Then("Сравнение архивных данных \'iCore2_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
    testRunner.When("Чтение исходных архивных данных \'resVar_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
    testRunner.Then("Сравнение архивных данных \'iCore2_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
    testRunner.When("Чтение исходных архивных данных \'resVar_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    testRunner.Then("Сравнение архивных данных \'iCore2_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
    testRunner.When("Чтение исходных архивных данных \'resVar_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
    testRunner.Then("Сравнение архивных данных \'iCore2_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
    testRunner.When("Чтение исходных архивных данных \'resVar_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
    testRunner.Then("Сравнение архивных данных \'iCore2_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
    testRunner.When("Чтение исходных архивных данных \'resVar_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
    testRunner.Then("Сравнение архивных данных \'iCore2_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
    testRunner.When("Чтение исходных архивных данных \'resVar_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
    testRunner.Then("Сравнение архивных данных \'iCore2_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
    testRunner.When("Чтение исходных архивных данных \'resVar_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("Сравнение архивных данных \'iCore2_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
    testRunner.When("Чтение исходных архивных данных \'resVar_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
    testRunner.Then("Сравнение архивных данных \'iCore2_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
    testRunner.When("Чтение исходных архивных данных \'resVar_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    testRunner.Then("Сравнение архивных данных \'iCore2_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
    testRunner.When("Чтение исходных архивных данных \'resVar_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
    testRunner.Then("Сравнение архивных данных \'iCore2_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
    testRunner.When("Чтение исходных архивных данных \'resVar_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 42
    testRunner.Then("Сравнение архивных данных \'iCore2_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
    testRunner.When("Чтение исходных архивных данных \'resVar_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
    testRunner.Then("Сравнение архивных данных \'iCore2_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
    testRunner.When("Чтение исходных архивных данных \'resVar_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
    testRunner.Then("Сравнение архивных данных \'iCore2_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
    testRunner.When("Чтение исходных архивных данных \'resVar_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
    testRunner.Then("Сравнение архивных данных \'iCore2_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.cpu715_Red_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_Cpu715_Red_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.cpu715_Red_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 54
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 55
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 56
 testRunner.Given("Связь с 1 устройством \'cpu715_Red\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 58
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 59
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 60
 testRunner.When("Чтение исходных архивных данных \'resVar_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
    testRunner.When("Чтение исходных архивных данных \'resVar_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 63
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 64
    testRunner.When("Чтение исходных архивных данных \'resVar_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
    testRunner.When("Чтение исходных архивных данных \'resVar_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 67
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
    testRunner.When("Чтение исходных архивных данных \'resVar_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 69
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
    testRunner.When("Чтение исходных архивных данных \'resVar_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
    testRunner.When("Чтение исходных архивных данных \'resVar_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
    testRunner.When("Чтение исходных архивных данных \'resVar_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
    testRunner.When("Чтение исходных архивных данных \'resVar_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 77
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
    testRunner.When("Чтение исходных архивных данных \'resVar_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 79
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
    testRunner.When("Чтение исходных архивных данных \'resVar_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 81
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
    testRunner.When("Чтение исходных архивных данных \'resVar_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 83
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
    testRunner.When("Чтение исходных архивных данных \'resVar_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 85
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
    testRunner.When("Чтение исходных архивных данных \'resVar_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 87
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
    testRunner.When("Чтение исходных архивных данных \'resVar_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 89
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
    testRunner.When("Чтение исходных архивных данных \'resVar_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 91
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
    testRunner.When("Чтение исходных архивных данных \'resVar_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
    testRunner.Then("Сравнение архивных данных \'cpu715_Red_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.cpu715_Clust_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_Cpu715_Clust_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.cpu715_Clust_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 99
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 100
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 101
 testRunner.Given("Связь с 1 устройством \'cpu715_Cluster\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 102
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 103
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 104
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 105
 testRunner.When("Чтение исходных архивных данных \'resVar_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 106
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 107
    testRunner.When("Чтение исходных архивных данных \'resVar_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 108
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
    testRunner.When("Чтение исходных архивных данных \'resVar_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 110
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 111
    testRunner.When("Чтение исходных архивных данных \'resVar_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
    testRunner.When("Чтение исходных архивных данных \'resVar_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 114
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
    testRunner.When("Чтение исходных архивных данных \'resVar_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 116
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
    testRunner.When("Чтение исходных архивных данных \'resVar_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 118
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 119
    testRunner.When("Чтение исходных архивных данных \'resVar_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 120
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 121
    testRunner.When("Чтение исходных архивных данных \'resVar_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 122
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
    testRunner.When("Чтение исходных архивных данных \'resVar_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 124
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
    testRunner.When("Чтение исходных архивных данных \'resVar_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 126
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 127
    testRunner.When("Чтение исходных архивных данных \'resVar_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 128
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 129
    testRunner.When("Чтение исходных архивных данных \'resVar_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 130
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 131
    testRunner.When("Чтение исходных архивных данных \'resVar_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 132
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 133
    testRunner.When("Чтение исходных архивных данных \'resVar_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 134
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 135
    testRunner.When("Чтение исходных архивных данных \'resVar_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 136
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 137
    testRunner.When("Чтение исходных архивных данных \'resVar_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 138
    testRunner.Then("Сравнение архивных данных \'cpu715_Cluster_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.cpu850_Red_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_Cpu850_Red_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.cpu850_Red_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 144
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 145
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 146
 testRunner.Given("Связь с 1 устройством \'CPU850_RED\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 147
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 148
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 149
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 150
 testRunner.When("Чтение исходных архивных данных \'resVar_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 151
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 152
    testRunner.When("Чтение исходных архивных данных \'resVar_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 153
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 154
    testRunner.When("Чтение исходных архивных данных \'resVar_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 155
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 156
    testRunner.When("Чтение исходных архивных данных \'resVar_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 157
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 158
    testRunner.When("Чтение исходных архивных данных \'resVar_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 159
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 160
    testRunner.When("Чтение исходных архивных данных \'resVar_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 161
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 162
    testRunner.When("Чтение исходных архивных данных \'resVar_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 164
    testRunner.When("Чтение исходных архивных данных \'resVar_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 165
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 166
    testRunner.When("Чтение исходных архивных данных \'resVar_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 167
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 168
    testRunner.When("Чтение исходных архивных данных \'resVar_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 169
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 170
    testRunner.When("Чтение исходных архивных данных \'resVar_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 171
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 172
    testRunner.When("Чтение исходных архивных данных \'resVar_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 173
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 174
    testRunner.When("Чтение исходных архивных данных \'resVar_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 175
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 176
    testRunner.When("Чтение исходных архивных данных \'resVar_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 177
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 178
    testRunner.When("Чтение исходных архивных данных \'resVar_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 179
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 180
    testRunner.When("Чтение исходных архивных данных \'resVar_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 181
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 182
    testRunner.When("Чтение исходных архивных данных \'resVar_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 183
    testRunner.Then("Сравнение архивных данных \'cpu850_Red_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.GwEx_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_GwEx_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.GwEx_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 188
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 189
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 190
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 191
 testRunner.Given("Связь с 1 устройством \'GwExch_v1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 192
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 193
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 194
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 195
 testRunner.When("Чтение исходных архивных данных \'GEv1_Var_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 196
    testRunner.Then("Сравнение архивных данных \'GwE_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 197
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 198
    testRunner.Then("Сравнение архивных данных \'GwE_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 199
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 200
    testRunner.Then("Сравнение архивных данных \'GwE_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 201
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 202
    testRunner.Then("Сравнение архивных данных \'GwE_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 203
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 204
    testRunner.Then("Сравнение архивных данных \'GwE_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 205
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 206
    testRunner.Then("Сравнение архивных данных \'GwE_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 207
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 208
    testRunner.Then("Сравнение архивных данных \'GwE_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 209
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 210
    testRunner.Then("Сравнение архивных данных \'GwE_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 211
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 212
    testRunner.Then("Сравнение архивных данных \'GwE_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 213
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 214
    testRunner.Then("Сравнение архивных данных \'GwE_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 215
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 216
    testRunner.Then("Сравнение архивных данных \'GwE_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 217
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 218
    testRunner.Then("Сравнение архивных данных \'GwE_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 219
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 220
    testRunner.Then("Сравнение архивных данных \'GwE_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 221
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 222
    testRunner.Then("Сравнение архивных данных \'GwE_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 223
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 224
    testRunner.Then("Сравнение архивных данных \'GwE_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 225
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 226
    testRunner.Then("Сравнение архивных данных \'GwE_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 227
    testRunner.When("Чтение исходных архивных данных \'GEv1_Var_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 228
    testRunner.Then("Сравнение архивных данных \'GwE_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.GwEx2_TimeStamp")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("Redmine_7528")]
        [NUnit.Framework.CategoryAttribute("package_Known_Bugs_GwEx2_TransmitArcVals")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_GwEx2_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "Redmine_7528",
                    "package_Known_Bugs_GwEx2_TransmitArcVals",
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.GwEx2_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 235
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 236
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 237
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 238
 testRunner.Given("Связь с 1 устройством \'GwExch_2_v1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 239
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 240
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 241
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 242
 testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_BOOL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 243
    testRunner.Then("Сравнение архивных данных \'GwE2_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 244
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_BYTE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 245
    testRunner.Then("Сравнение архивных данных \'GwE2_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 246
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_WORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 247
    testRunner.Then("Сравнение архивных данных \'GwE2_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 248
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_DWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 249
    testRunner.Then("Сравнение архивных данных \'GwE2_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 250
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_LWORD\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 251
    testRunner.Then("Сравнение архивных данных \'GwE2_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 252
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_SINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 253
    testRunner.Then("Сравнение архивных данных \'GwE2_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 254
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_INT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 255
    testRunner.Then("Сравнение архивных данных \'GwE2_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 256
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_DINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 257
    testRunner.Then("Сравнение архивных данных \'GwE2_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 258
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_LINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 259
    testRunner.Then("Сравнение архивных данных \'GwE2_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 260
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_USINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 261
    testRunner.Then("Сравнение архивных данных \'GwE2_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 262
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_UINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 263
    testRunner.Then("Сравнение архивных данных \'GwE2_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 264
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_UDINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 265
    testRunner.Then("Сравнение архивных данных \'GwE2_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 266
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_ULINT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 267
    testRunner.Then("Сравнение архивных данных \'GwE2_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 268
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_REAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 269
    testRunner.Then("Сравнение архивных данных \'GwE2_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 270
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_LREAL\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 271
    testRunner.Then("Сравнение архивных данных \'GwE2_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 272
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_TIME\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 273
    testRunner.Then("Сравнение архивных данных \'GwE2_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 274
    testRunner.When("Чтение исходных архивных данных \'GwE2v1_Var_DATE\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 275
    testRunner.Then("Сравнение архивных данных \'GwE2_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.OpcDa_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_OpcDa_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.OpcDa_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 280
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 281
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 282
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 283
 testRunner.Given("Связь с 1 устройством \'OpcDa_Subs\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 284
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 285
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 286
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 287
 testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_bool\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 288
    testRunner.Then("Сравнение архивных данных \'OpcDa_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 289
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_byte\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 290
    testRunner.Then("Сравнение архивных данных \'OpcDa_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 291
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_word\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 292
    testRunner.Then("Сравнение архивных данных \'OpcDa_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 293
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_dword\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 294
    testRunner.Then("Сравнение архивных данных \'OpcDa_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 295
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_lword\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 296
    testRunner.Then("Сравнение архивных данных \'OpcDa_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 297
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_sint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 298
    testRunner.Then("Сравнение архивных данных \'OpcDa_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 299
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_int\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 300
    testRunner.Then("Сравнение архивных данных \'OpcDa_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 301
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_dint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 302
    testRunner.Then("Сравнение архивных данных \'OpcDa_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 303
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_lint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 304
    testRunner.Then("Сравнение архивных данных \'OpcDa_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 305
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_usint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 306
    testRunner.Then("Сравнение архивных данных \'OpcDa_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 307
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_uint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 308
    testRunner.Then("Сравнение архивных данных \'OpcDa_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 309
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_udint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 310
    testRunner.Then("Сравнение архивных данных \'OpcDa_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 311
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_ulint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 312
    testRunner.Then("Сравнение архивных данных \'OpcDa_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 313
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_real\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 314
    testRunner.Then("Сравнение архивных данных \'OpcDa_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 315
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_lreal\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 316
    testRunner.Then("Сравнение архивных данных \'OpcDa_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 317
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_time\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 318
    testRunner.Then("Сравнение архивных данных \'OpcDa_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 319
    testRunner.When("Чтение исходных архивных данных \'OpcDa_Subs_VAR_date\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 320
    testRunner.Then("Сравнение архивных данных \'OpcDa_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.OpcProxy_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_OpcProxy_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.OpcProxy_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 325
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 326
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 327
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 328
 testRunner.Given("Связь с 1 устройством \'OpcDaProxy_Subs\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 329
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 330
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 331
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 332
 testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_bool\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 333
    testRunner.Then("Сравнение архивных данных \'OpcProxy_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 334
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_byte\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 335
    testRunner.Then("Сравнение архивных данных \'OpcProxy_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 336
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_word\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 337
    testRunner.Then("Сравнение архивных данных \'OpcProxy_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 338
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_dword\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 339
    testRunner.Then("Сравнение архивных данных \'OpcProxy_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 340
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_lword\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 341
    testRunner.Then("Сравнение архивных данных \'OpcProxy_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 342
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_sint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 343
    testRunner.Then("Сравнение архивных данных \'OpcProxy_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 344
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_int\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 345
    testRunner.Then("Сравнение архивных данных \'OpcProxy_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 346
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_dint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 347
    testRunner.Then("Сравнение архивных данных \'OpcProxy_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 348
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_lint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 349
    testRunner.Then("Сравнение архивных данных \'OpcProxy_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 350
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_usint\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 351
    testRunner.Then("Сравнение архивных данных \'OpcProxy_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 352
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_uint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 353
    testRunner.Then("Сравнение архивных данных \'OpcProxy_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 354
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_udint\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 355
    testRunner.Then("Сравнение архивных данных \'OpcProxy_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 356
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_ulint\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 357
    testRunner.Then("Сравнение архивных данных \'OpcProxy_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 358
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_real\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 359
    testRunner.Then("Сравнение архивных данных \'OpcProxy_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 360
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_lreal\'.\'Значение\' из \'ArcWork\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 361
    testRunner.Then("Сравнение архивных данных \'OpcProxy_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 362
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_time\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 363
    testRunner.Then("Сравнение архивных данных \'OpcProxy_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 364
    testRunner.When("Чтение исходных архивных данных \'OpcProxy_Subs_VAR_date\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 365
    testRunner.Then("Сравнение архивных данных \'OpcProxy_DATE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.OpcUa_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_OpcUa_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.OpcUa_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 370
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 371
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 372
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 373
 testRunner.Given("Связь с 1 устройством \'OpcUa_ASt5000_Lin\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 374
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 375
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 376
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 377
 testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_bool\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 378
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_BOOL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 379
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_byte\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 380
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_BYTE\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 381
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_word\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 382
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_WORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 383
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_dword\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 384
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_DWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 385
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_lword\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 386
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_LWORD\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 387
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_sint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 388
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_SINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 389
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_int\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 390
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_INT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 391
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_dint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 392
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_DINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 393
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_lint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 394
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_LINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 395
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_usint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 396
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_USINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 397
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_uint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 398
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_UINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 399
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_udint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 400
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_UDINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 401
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_ulint\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 402
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_ULINT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 403
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_real\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 404
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_REAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 405
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_lreal\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 406
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_LREAL\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 407
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_time\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 408
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_TIME\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 409
    testRunner.When("Чтение исходных архивных данных \'OpcUa_PARAM_DT\'.\'Значение\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 410
    testRunner.Then("Сравнение архивных данных \'OpcUa_PARAM_DT\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GwE2ex.Snmp_TimeStamp")]
        [NUnit.Framework.CategoryAttribute("fromMirror")]
        [NUnit.Framework.CategoryAttribute("fromGate")]
        [NUnit.Framework.CategoryAttribute("EpicTimeStamp")]
        [NUnit.Framework.CategoryAttribute("StoryGwE2ex")]
        [NUnit.Framework.CategoryAttribute("parentSuite2_ExchUtils_GwE2ex")]
        [NUnit.Framework.CategoryAttribute("suiteTimeStamp")]
        public void GwE2Ex_Snmp_TimeStamp()
        {
            string[] tagsOfScenario = new string[] {
                    "fromMirror",
                    "fromGate",
                    "EpicTimeStamp",
                    "StoryGwE2ex",
                    "parentSuite2_ExchUtils_GwE2ex",
                    "suiteTimeStamp"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GwE2ex.Snmp_TimeStamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 417
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 418
 testRunner.Given("Шлюзы \'work\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 419
    testRunner.Given("Архив \'ArcWork\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 420
 testRunner.Given("Связь с 1 устройством \'Snmp_v2_NetSw28\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 421
    testRunner.Given("Шлюз \'DataReceiver\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 422
    testRunner.Given("Архив \'ArcReciv\' в работе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 423
 testRunner.Given("Связь с 2 устройством \'GwEx2ex_1\' в норме", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 424
 testRunner.When("Чтение исходных архивных данных \'UpTime\'.\'\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 425
    testRunner.Then("Сравнение архивных данных \'SnmpV2_UpTime\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 426
    testRunner.When("Чтение исходных архивных данных \'Channel 09\\InOctets\'.\'\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 427
    testRunner.Then("Сравнение архивных данных \'SnmpV2_InOctets_09\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 430
    testRunner.When("Чтение исходных архивных данных \'Channel 10\\InOctets\'.\'\' из \'ArcWork\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 431
    testRunner.Then("Сравнение архивных данных \'SnmpV2_InOctets_10\'.\'Значение\' из \'ArcReciv\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
